// Turn whisper token-level captions into word-level karaoke chunks (≤6 words),
// preserving the EXACT spoken words and their real timings.
// Usage: node build-words.mjs public/raw/clip.captions.json src/data/clipWords.ts CHUNKS
import fs from "fs";

const [, , inPath, outPath, constName = "CHUNKS"] = process.argv;
if (!inPath || !outPath) {
  console.error("usage: node build-words.mjs <captions.json> <out.ts> [CONST_NAME]");
  process.exit(1);
}

const raw = JSON.parse(fs.readFileSync(inPath, "utf8"));

// 1) merge sub-word tokens into whole words.
// A whisper token that starts with a space begins a new word; anything else
// (continuations like "M"/"DC", punctuation, decimals) attaches to the previous.
const words = [];
for (const tk of raw) {
  const t = tk.text.replace(/\s+/g, " ");
  const trimmed = t.trim();
  const isNew = t.startsWith(" ") || words.length === 0;
  if (trimmed === "") {
    if (words.length) words[words.length - 1].e = tk.endMs;
    continue;
  }
  if (isNew) {
    words.push({ t: trimmed, s: tk.startMs, e: tk.endMs });
  } else {
    const prev = words[words.length - 1];
    prev.t += trimmed;
    prev.e = tk.endMs;
  }
}

// 2) group into chunks of ≤6 words, breaking at sentence / clause ends.
const chunks = [];
let cur = [];
const flush = () => {
  if (!cur.length) return;
  chunks.push({ s: cur[0].s, e: cur[cur.length - 1].e, words: cur });
  cur = [];
};
for (const w of words) {
  cur.push(w);
  const endsSentence = /[.!?]["')\]]?$/.test(w.t);
  const endsClause = /[,;:]["')\]]?$/.test(w.t);
  if (cur.length >= 6 || endsSentence || (endsClause && cur.length >= 4)) flush();
}
flush();

const out =
  `// AUTO-GENERATED by build-words.mjs from ${inPath}\n` +
  `// Word-level karaoke chunks (exact spoken words + real timings, ms).\n` +
  `import type { KChunk } from "../components/KaraokeCaptions";\n` +
  `export const ${constName}: KChunk[] = ${JSON.stringify(chunks)};\n`;

fs.writeFileSync(outPath, out);
console.log(`words: ${words.length}  chunks: ${chunks.length} → ${outPath}`);
console.log(
  chunks
    .slice(0, 8)
    .map((c) => `[${(c.s / 1000).toFixed(1)}-${(c.e / 1000).toFixed(1)}] ${c.words.map((w) => w.t).join(" ")}`)
    .join("\n"),
);
